# Generated by Django 6.0.8 on 2026-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='stage_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'Вручную'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'По дням недели')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='workflow',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=64),
        ),
        migrations.AlterField(
            model_name='workflowoperation',
            name='operation_type',
            field=models.CharField(choices=[('remove_duplicates', 'Удалить дубликаты'), ('drop_columns', 'Удалить столбцы'), ('filter', 'Фильтровать'), ('sort', 'Сортировать'), ('find_replace', 'Найти и заменить'), ('remove_empty_rows', 'Удалить пустые строки'), ('normalize_phone', 'Нормализовать телефон'), ('normalize_text', 'Нормализовать текст'), ('normalize_dates', 'Нормализовать даты'), ('convert_type', 'Изменить тип столбца'), ('extract', 'Извлечь из текста'), ('split', 'Разделить таблицу'), ('append', 'Добавить данные')], max_length=40),
        ),
    ]
