# Generated by Django 6.0.8 on 2026-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_execution_stage_errors_workflow_last_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='email_recipient',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
