# Generated by Django 6.0.8 on 2026-08-20 12:50

import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=files.models.user_upload_path)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (XLSX)'), ('csv', 'CSV')], max_length=8)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('rows_count', models.PositiveIntegerField(blank=True, null=True)),
                ('columns_count', models.PositiveIntegerField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.user_result_path)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (XLSX)'), ('csv', 'CSV')], max_length=8)),
                ('original_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(default='', max_length=255)),
                ('rows_before', models.PositiveIntegerField(blank=True, null=True)),
                ('rows_after', models.PositiveIntegerField(blank=True, null=True)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='files.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
